### PR TITLE
Added some tests for XML parsing from the XML conformance test suite

### PR DESCRIPTION
**Pull request by Devasta**
Hello,

I have started work on building out tests for the XML parser for this project. Attached is a PR with the efforts so far. It contains all test files as found on the [XML W3C Conformance Test Suite 20130923](https://www.w3.org/XML/Test/), but only James Clarks suite is built out so far. If these efforts meet with your approval I will continue on the other sections.

This is a very large PR because each individual test is across multiple files in the Test Suite, which contains 3,386 files, but the number of files with code changes are very low, and future PRs will be much smaller.

- The file "parsexml.rs" has the below additions to allow comparison of the parsed documents, this will be useful for when parsed XML with DTDs is checked against canonical XML.
image
- The tests folder now has a folder called "conformance", that contains all test files. The folder "xmlconf" is the W3C test suite, the rest are the test files.
image
- You can run "cargo test conformance", and you will see most pass, and no failures. A large number are set to ignore pending the buildout of the needed functionality for the tests (specifically, DTDs and escape characters).
image

I am learning Rust as I go, this will be the first proper PR I've contributed to a project, so if these tests do not meet your standards please don't hesitate to let me know.

Many thanks in advance for reviewing this PR, let me know if any questions.

Regards,

Dan

### CODE REVIEW

**Comment by ballsteve** [comment]
Hi Daniel,

Thanks for making a contribution to this project! I've also been learning Rust for the past 18 months or so.

This project has a massive scope, so getting some help with it is very much appreciated!

I'll do a review of this PR right now.

**Review by ballsteve — APPROVED** [review]
These changes look fine

**Comment by Devasta** [comment]
> Hi Daniel,
> 
> Thanks for making a contribution to this project! I've also been learning Rust for the past 18 months or so.
> 
> This project has a massive scope, so getting some help with it is very much appreciated!
> 
> I'll do a review of this PR right now.

No problem! Reading this code has given me a lot of stuff to learn about, looks like I'll need to crash course on parser combinators. 😄

**Comment by ballsteve** [comment]
Hi Daniel,

Yes, they’re pretty tricky!

Can I make one request? Please make your contributions to the ‘dev’ branch. I do my development work on that branch, make sure there are no errors, and minimal warnings, and then merge into the main branch to do releases.

Cheers,
Steve Ball

**Comment by Devasta** [comment]
Will do!

**Pull request merged**
