### PR TITLE
Feb2 2024

### PR DESCRIPTION
**Pull request by ballsteve**
This PR includes a bunch of features to get us closer to the 1.0 release:

* xsl:value-of
* generate-id() function
* current() function
* key() function and xsl:key
* system-property() function
* Callable components: named templates and xsl:function

Also a number of cleanups and codebase improvements:

* Retired intmuttree in favour of smite
* Added string parameter to ParseError::NotWellFormed to improve error messages
* Moved tests from testutils macros to modules in the tests folder

### CODE REVIEW

**Comment by Devasta** [comment]
Hi Steve,

I'm reviewing this at the moment, I gotta say I really like how Smite is working out. :)

**Comment by Devasta** [comment]
Hi Steve,

I've made some small adjustments to fix those parser failing tests, mind taking a quick look? Can merge then.

**Comment by ballsteve** [comment]
Yes, the smite module is looking much better. It's nice how code evolves over time.

The changes to the XML parser look good. However, there are now a few errors coming up in other tests. I'll fix those and let you know when the changes are committed.

**Comment by Devasta** [comment]
These changes look good in any case.

Thanks for all your work on this! :)

**Comment by Devasta** [comment]
Just ran them there, the docs pass on my machine but admittedly its a fairly beefy gamer laptop.

**Comment by ballsteve** [comment]
There's a lot of warnings being generated by the validator module; particularly it doesn't like the way you're naming functions. Eg:

warning: function `oneOrMore` should have a snake case name
   --> src/validators/relaxng/derive.rs:468:4
    |
468 | fn oneOrMore(pat: Pattern) -> Pattern {
    |    ^^^^^^^^^ help: convert the identifier to snake case: `one_or_more`

Although it doesn't bother me too much, if rustc isn't happy then we'd better fix it ;-)

**Comment by Devasta** [comment]
I'll get it fixed, I tend to ignore most warnings until a final release, bad habit I know.

I'm hoping to have more work on it done in the next few days but until I have a decent number of tests passing I'll probably hide it from being publically available, will let you know.

**Pull request merged**
