### PR TITLE
Starting work on CDATA Support

### PR DESCRIPTION
**Pull request by Devasta**
Hi Steve,

I've started some work on getting CDATA support built into the parser, let me know what you think. I still need to do some work on catching invalid characters and the like so will be make more changes regardless.

Regards

Dan

### CODE REVIEW

**Review by ballsteve — APPROVED** [review]
Looks good.

**Comment by ballsteve** [comment]
I have to check whether CDATA sections can be nested.

**Comment by ballsteve** [comment]
CDATA sections cannot be nested, so don't worry about trying to support that.

**Comment by Devasta** [comment]
Thanks

By the way, I can see the commit seems very large because the indentation on a bunch fo stuff has changed, think that was my IDE. Sorry about that, won't happen again!

**Comment by ballsteve** [comment]
I’ve made a couple of changes to variable names since rustc doesn’t like capitals. See my latest push.

Cheers,
Steve

**Pull request merged**
