### PR TITLE
Re-implemented special character escaping in get_canonical

### PR DESCRIPTION
**Pull request by ballsteve**
Fixed failing test. This was due to get_canonical not escaping special characters as per Canonical XML spec, section 3.4.

### CODE REVIEW

**Comment by Devasta** [comment]
`failures:
    conformance::xml::ibm_valid::ibmvalid_p01ibm01v01xml
    conformance::xml::ibm_valid::ibmvalid_p39ibm39v01xml
    conformance::xml::ibm_valid::ibmvalid_p40ibm40v01xml
    conformance::xml::ibm_valid::ibmvalid_p41ibm41v01xml
    conformance::xml::ibm_valid::ibmvalid_p42ibm42v01xml
    conformance::xml::ibm_valid::ibmvalid_p44ibm44v01xml
    conformance::xml::ibm_valid::ibmvalid_p45ibm45v01xml
    conformance::xml::ibm_valid::ibmvalid_p47ibm47v01xml
    conformance::xml::ibm_valid::ibmvalid_p51ibm51v01xml
    conformance::xml::ibm_valid::ibmvalid_p52ibm52v01xml
    conformance::xml::ibm_valid::ibmvalid_p54ibm54v02xml
    conformance::xml::ibm_valid::ibmvalid_p54ibm54v03xml
    conformance::xml::ibm_valid::ibmvalid_p55ibm55v01xml
    conformance::xml::ibm_valid::ibmvalid_p56ibm56v02xml
    conformance::xml::ibm_valid::ibmvalid_p56ibm56v03xml
    conformance::xml::ibm_valid::ibmvalid_p56ibm56v04xml
    conformance::xml::ibm_valid::ibmvalid_p56ibm56v05xml
    conformance::xml::ibm_valid::ibmvalid_p56ibm56v06xml
    conformance::xml::ibm_valid::ibmvalid_p56ibm56v07xml
    conformance::xml::ibm_valid::ibmvalid_p56ibm56v09xml
    conformance::xml::ibm_valid::ibmvalid_p56ibm56v10xml
    conformance::xml::ibm_valid::ibmvalid_p57ibm57v01xml
    conformance::xml::ibm_valid::ibmvalid_p58ibm58v01xml
    conformance::xml::ibm_valid::ibmvalid_p58ibm58v02xml
    conformance::xml::ibm_valid::ibmvalid_p59ibm59v01xml
    conformance::xml::ibm_valid::ibmvalid_p59ibm59v02xml
    conformance::xml::ibm_valid::ibmvalid_p60ibm60v01xml
    conformance::xml::ibm_valid::ibmvalid_p60ibm60v02xml
    conformance::xml::ibm_valid::ibmvalid_p60ibm60v03xml
    conformance::xml::ibm_valid::ibmvalid_p60ibm60v04xml
    conformance::xml::ibm_valid::ibmvalid_p66ibm66v01xml
    conformance::xml::ibm_valid::ibmvalid_p67ibm67v01xml
    conformance::xml::sun_valid::element
    conformance::xml::sun_valid::sa01
    conformance::xml::sun_valid::sa05
    conformance::xml::sun_valid::vpe03
    conformance::xml::xmltest_valid_sa::validsa044
    conformance::xml::xmltest_valid_sa::validsa047
    conformance::xml::xmltest_valid_sa::validsa059
    conformance::xml::xmltest_valid_sa::validsa092
    conformance::xml::xmltest_valid_sa::validsa093
    conformance::xml::xmltest_valid_sa::validsa116

test result: FAILED. 1905 passed; 42 failed; 429 ignored; 0 measured; 0 filtered out; finished in 1.29s
`

Seeing a lot of failures on Windows, investigating.

**Comment by ballsteve** [comment]
I must have made a mistake when checking in the code, coz I have fixed all of those. I'll look at what's happened to my git repo.

**Comment by Devasta** [comment]
Have just pushed some changes to this branch, think its good now, we can merge when ready.

**Comment by ballsteve** [comment]
All tests are passing now

**Pull request merged**
