### PR TITLE
XML DTD ID/ID REF support for attributes.

### PR DESCRIPTION
**Pull request by Devasta**
Hi Steve,

Started work on support for XML IDs.

- Smite has been slightly tweaked to have the is_id and is_idrefs properties
- The taggedelem and emptyelem have been merged into a single "element" function, as they were mostly the same.
- Attribute creation is now done in the new elem function, as the ATTList DTD declarations have to be checked before creation.
- Have adjusted the parser to check for duplicate XML IDs as well as missing IDs for IDREFs
- The ParserConfig has been updated to enable/disable this feature. It is on by default
- The transformation steps have not yet been updated to handle these new capabilities, just setting is_id and is_idrefs to false when creating attributes. Will need to research some more about what needs to happen here.
- Elements do not yet have IDs, will need to add that at a later stage.
- xml:ID is not part of this pull request, I need to do a bit of reading on those.

### CODE REVIEW

**Comment by Devasta** [comment]
Should mention, I'm happy to hold off on this one until after the latest version release, the namespace changes are big enough.

**Comment by ballsteve** [comment]
This is a good development, but we need to make sure the design supports ID/IDREF, xml:id, id(), and also is compatible with key().

Let's hold on to this PR until the 1.1 release is done.

**Comment by Devasta** [comment]
Sounds good, I'll take a look into those points and come back with some updates.

**Comment by ballsteve** [comment]
Instead of having is_id, is_idrefs arguments to new_attribute(), could we use the Value being passed in as the attribute value? That is, Value::ID("x"), Value::IDREF("x"), Value::IDREFS("x y z")

If the attribute is declared to be of type ID or IDREF or IDREFS then the value being passed in must be that type (or coercible to that type).

This design might work better in future when we build support for XML Schema data types.

**Comment by Devasta** [comment]
Yes we should! I'll get the changes made and we can look at this again when ready.

**Comment by Devasta** [comment]
Closing this, gonna reopen with a cleaner git history.

**Pull request closed without merging**
