### PR TITLE
XML Namespace Redesign

### PR DESCRIPTION
**Pull request by ballsteve**
Support for XML Namespaces has been redesigned and reimplemented. This has achieved a significant improvement in performance for parsing XML documents, as well as transformations.

In the new design, namespace nodes represent namespace declarations. These are mainly used when serialising a tree. The iterator namespace_iter() will return all in-scope namespace nodes. The namespace module provides a static mapping of prefix to namespace URI, NamespaceMap, that is used in the XML parser and transformations.

QualifiedName now stores Rc<Value>, instead of String. Elements and Attributes now use Rc<QualifiedName>, instead of QualifiedName. Namespaces use Rc<Value>. This allows names, and components of names, to be shared instead of being copied, resulting in the aforementioned significant performance increases. NamespaceMaps are also Rc-shared to avoid cloning.

The parser has a facility for interning values. This ensures that parsed strings are shared. However, sharing only occurs within the document being parsed. The next step will be to globally intern values, which will speed up value equality comparisons (comparing pointers rather than content), increase sharing (reducing memory consumption), and reduce copying/cloning. However, there is a risk of memory leakage if done in a naive fashion.

Documents are now created using the new_document() method of the Node trait. This makes document creation consistent with other node creation.

### CODE REVIEW

**Comment by Devasta** [comment]
Hi Steve, I'm on a business  this week but I'll be back by Sunday, will give it a review when I can but it'll probably be Tuesday at the earliest.

**Comment by Devasta** [comment]
Hi Steve,

conformance::xml::eduni_namespaces_10_notwf::rmtns10009
conformance::xml::eduni_namespaces_10_notwf::rmtns10010
conformance::xml::eduni_namespaces_10_notwf::rmtns10011
conformance::xml::eduni_namespaces_10_notwf::rmtns10012
conformance::xml::eduni_namespaces_10_notwf::rmtns10035
conformance::xml::eduni_namespaces_10_notwf::rmtns10036
conformance::xml::eduni_namespaces_11_notwf::rmtns11005
conformance::xml::eduni_namespaces_errata1e_notwf::rmtnse1013a
conformance::xml::eduni_namespaces_errata1e_notwf::rmtnse1013b
conformance::xml::ibm_notwf::ibmnotwf_p40ibm40n05xml
conformance::xml::ibm_notwf::ibmnotwf_p44ibm44n04xml
conformance::xml::oasis_notwf::op44fail5
conformance::xml::xmltest_notwf_sa::notwfsa038

Grabbed a chance to run tests and these are failing on my machine, will check when I get a chance.

**Comment by ballsteve** [comment]
Yes, those tests are failing for me as well. Let me know when you've had a look. I probably won't be able to look at them until later this week.

**Comment by Devasta** [comment]
Right, there is no duplicate checking on the xmlns declarations, but thats easy to fix.

How would you like to handle xmlns declarations across children?

`<doc>
	<element1 xmlns:a="namespace1"/>
	<a:element2/>
</doc>`

Currently parses, assigning namespace1 to element2.

The intention with the vector of hashmaps was that its depth would only ever be the amount of ancestors between it and the root node, so when we ran down some child nodes we'd always push onto the vector for dealing with that element, but pop off before we move onto the child.

I could look to create a specialized many0 combinator that resets the namespaces between iteration?

**Comment by Devasta** [comment]
Playing around, the new combinator I suggested above seems to be the best way to fix it, I think I'll go with that. Just need to implement duplicate checking and we'll be sorted.

**Comment by ballsteve** [comment]
Hi Daniel,

OK, sounds good.

Cheers,
Steve

**Comment by Devasta** [comment]
Just pushed some fixes to this branch, some duplicate checking for attributes.

xslt_issue_58 is failing, we serialize namespaces based on the namespace nodes on the element but don't add any namespace nodes on the literal_element construct.

**Comment by ballsteve** [comment]
OK, I'll take a look at the literal_element transform

**Comment by ballsteve** [comment]
Pushed a change to fix Issue 58. When literal_element is creating the element, it checks if it is in a namespace. If so, it creates and adds a Namespace node. This fixes the test (with a little adjustment to the test itself).

However, because elements are created bottom-up this will result in lots of redundant Namespace declarations. The fix for that is to remove redundant declarations from the child element nodes as part of literal_element. I've left that as a TODO.

Also, need to add namespace declarations for attributes, if required. Also a TODO.

**Comment by Devasta** [comment]
This is looking good, we'll need to review documentation as part of the prep for the next release but can merge this now.

**Pull request merged**
