### PR TITLE
OASIS conformance tests addition

### PR DESCRIPTION
**Pull request by Devasta**
Hi Steve,

Some more tests for you, this time the OASIS suite.

Note: There is now 534 passed; 4 failed; 240 ignored. The issues are below:

conformance::xml::oasis_notwf::op40fail4 --> Allowing spaces before element name (opening tag)
conformance::xml::oasis_notwf::op42fail1 --> Allowing spaces before element name (closing tag)
conformance::xml::oasis_notwf::op44fail1 --> Allowing spaces before element name (empty element)
conformance::xml::oasis_notwf::op44fail5 --> Allowing duplicate attributes

Should I raise issues for these or will I set to ignore for now?

Last bunch of units tests I'll add for now, will start looking at actual code contributions next.

### CODE REVIEW

**Comment by ballsteve** [comment]
Hi Daniel,

Please raise these as issues. Even if they are not fixed straight-away, it is important to note them and track their resolution.

Cheers,
Steve Ball

**Comment by Devasta** [comment]
Just making sure, thanks!

**Review by ballsteve — APPROVED** [review]
In function chordate, my style is to put more indenting into nested function calls.

However, this is a minor nitpick, so I'm approving the PR.

**Comment by Devasta** [comment]
Ah, sorry, didn't mean to push the escapes in until I sorted unicode codepoints too. (I'm good with computers I swear!).

I'll break it out into its own function when I sort those.

**Pull request merged**
