### PR TITLE
Parser dev2

### PR DESCRIPTION
**Pull request by Devasta**
Hi Steve,

Big changes within:

Changes:

- Big rewrite of the XML parser. It still uses the same strategy of parser combinators, however instead of using nom I've implemented a new set of combinators that work mostly the same; instead of a &str as input they accept a ParserInput Struct that can carry stuff like entities along with various iterators for the document it parses. The other parsers such as for xpath are still using nom, haven't looked at changing but it'd be straightforward I think.
- Added all remaining XML conformance tests. Lots of them still failing, will work on resolving (which will mean eventually needing to validate DTDs, which I have no idea how to implement).
- A new test "bigfile" included, parsing a document called "45M.xml". The contents of this file is a simple document which has the following:
    <big>
        <bigkid bigattr="bigattrval">bigtext</bigkid>
        
    </big>
 
I'll be using that for profiling and trying to figure out where the bottlenecks are, I've been using flamegraph to do it. 45 megabytes isn't a big file for more peoples uses, but I think we'd get in trouble if I loaded a bigger one to github!

I intend to make smaller, more frequent changes going forward, but the replacing of the main parser was an all-or-nothing change so had to be a large chunk, and the longer I left this one go the further everything was diverging from your work. I'll get namespaces sorted next and sort the remaining conformance errors.

Let me know if you feel additional work is required to bring this PR up to scratch.

### CODE REVIEW

**Comment by ballsteve** [comment]
Hi Daniel,

That sounds like great progress!

I’ll merge my dev branch with your changes, and take a look.

Cheers,
Steve

**Comment by ballsteve** [comment]
Hi Daniel,

BTW, Romeo has asked me to give a talk on xrust to the Stuttgart Rust User Group. That will be today at 6pm CET (ie Thursday 15th, or Friday 16th at 4am AEDT :-( ). I'll be mentioning your work on the XML parser.

**Comment by Devasta** [comment]
Really glad to hear that! Let me know how it goes. 😄

**Comment by ballsteve** [comment]
The talk for Stuttgart Rust User Group went well! There were only two problems: (1) I had to get up at 4am :-(, and (2) there was only enough time (0.5 hour talk) to give a high-level overview of Xrust, and some people wanted to get into the detail of trees and parsers. We may have to give more talks!

**Comment by Devasta** [comment]
1. Right, this one is my fault. Essentially, it started that the combinators would take a tuple with (document, offset, error) and then I used a type alias to clean up the code, but it continued to grow legs so I moved it all into the Parserinput struct with the alias remaining as (parserinput, error location). I could change the struct name to something like parserstate, or I could get rid of the type alias entirely. The usize that contains the location of the error I am hoping to extend out in future to provide details of what actually is going wrong.

2. Good catch! Will fix that now!

**Review by ballsteve — APPROVED** [review]
Looks good now

**Comment by ballsteve** [comment]
After merging this branch (which you can now delete, btw), the XSLT tests are failing because the parser is not handling XML Namespaces.

I'll take a look and see why this is not working correctly, but if you can advise on the state of namespace support that would be great!

Merry Xmas!

**Comment by Devasta** [comment]
Will be working on namespaces next. Sorry about that. I think I should be able to carry those along on the parser.

Merry christmas to you too!

**Comment by ballsteve** [comment]
Hi Daniel,

No worries.

I’ll let you get on with that, and eagerly await the result ;-)

In the meantime, I’m going to take a look at writing a transformation combinator (or at least thinking about it ;-)

Cheers, and Merry Xmas and New Year,
Steve

**Pull request merged**
